<?php
namespace PatrickBroens\Contentelements\ViewHelpers\Format;

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

use PatrickBroens\Contentelements\ViewHelpers\AbstractFrontendViewHelper;

/**
 * A view helper which returns a string with a class generated by the "layout" field
 */
class LayoutClassViewHelper extends AbstractFrontendViewHelper {

	/**
	 * Render the view helper
	 *
	 * @param int $key The key from the field "layout" in the database
	 * @param string $prefix The prefix for the class name
	 * @return string The class name
	 */
	public function render($key = 0, $prefix = 'ce-layout-') {
		$class = '';

		if ((int)$key !== 0) {
			$class = htmlspecialchars($prefix . $key);
		}

		return $class;
	}
}